### ISSUE TITLE
Shared test resources across tests not being shared

### ISSUE THREAD

**Issue by jamesdh** [micronaut-projects/micronaut-servlet#653]
### Expected Behavior

Multiple tests that make use of a Postgres container configured via test-resources will share the database container and not restart it for each separate test class. This is the default behavior as described in "Isolating Test Resources" under [5.2 JUnit Platform](https://micronaut-projects.github.io/micronaut-test-resources/latest/guide/#extensions-junit-platform)

### Actual Behaviour

Postgres container is restarted for every test class containing a `@MicronautTest` annotation. This nearly doubles our test runtime. Was able to work around it by appending `TC_REUSABLE` to the datasource URL as a la: `datasources.default.url: jdbc:tc:postgresql:16:///postgres;TC_REUSABLE=true`

### Steps To Reproduce

1. Given a fresh application and the following config: 
```yaml
datasources:
  default:
    url: jdbc:tc:postgresql:16:///postgres
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
test-resources:
  enabled: true
  containers:
    postgres:
      image-name: postgres:16
```
2. Add multiple test classes that make use of `@MicronautTest`
3. Run your tests while observing docker and you'll see the Postgres container being shutdown and brought back up in rapid fire succession. 

### Environment Information

MacOS 14.2.1
Java 21.0.2-tem
Docker Desktop 4.28.0

### Version

4.3.4
